authentication/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
)
from django.urls import path

from .views import signup_page, upload_profile_photo

urlpatterns = [
    path('', LoginView.as_view(
        template_name='authentication/login.html',
        redirect_authenticated_user=True,
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('change-password/', PasswordChangeView.as_view(
        template_name='authentication/password_change_form.html'),
        name='password_change'
    ),
    path('change-password-done/', PasswordChangeDoneView.as_view(
        template_name='authentication/password_change_done.html'),
        name='password_change_done'
    ),
    path('signup/', signup_page, name='signup'),
    path('change_profile_photo/', upload_profile_photo,
         name='change_profile_photo'),


]

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("home/", views.home, name="home"),
    path("photo/upload", views.photo_upload, name="photo_upload"),
    path("blog/create", views.blog_and_photo_upload, name="blog_create"),
    path("blog/<int:blog_id>", views.view_blog, name="view_blog"),
    path("blog/<int:blog_id>/edit", views.edit_blog, name="edit_blog"),
    path(
        "photo/upload-multiple/",
        views.create_multiple_photos,
        name="create_multiple_photos",
    ),
]

fotoblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('', include('blog.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    CREATOR = 'CREATOR'
    SUBSCRIBER = 'SUBSCRIBER'

    ROLES_CHOICES = ((CREATOR, 'Creator'), (SUBSCRIBER, 'Subscriber'))

    profile_photo = models.ImageField()
    role = models.CharField(max_length=30, choices=ROLES_CHOICES)

authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class LoginForm(forms.Form):
    username = forms.CharField(max_length=6)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)


class SignupForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = get_user_model()
        fields = ("username", "email",
                  "first_name", "last_name", "role")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class UploadProfilePhotoForm(forms.ModelForm):

    class Meta:
        model = get_user_model()
        fields = ("profile_photo",)

authentication/views.py
from django.conf import settings
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import SignupForm, UploadProfilePhotoForm

# class LoginPageView(View):
#     template_name = 'authentication/login.html'
#     form_class = forms.LoginForm

#     def get(self, request):
#         form = self.form_class()
#         message = ""
#         context = {'form': form, 'message': message}
#         return render(request, self.template_name, context)

#     def post(self, request):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             user = authenticate(
#                 username=form.cleaned_data['username'],
#                 password=form.cleaned_data['password'],
#             )
#             if user is not None:
#                 login(request, user)
#                 return redirect('home')
#         message = 'Login faild!'
#         context = {'form': form, 'message': message}
#         return render(request, self.template_name, context)

# def logout_user(request):
# logout(request)
# return redirect('login')


def signup_page(request):
    form = SignupForm()
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect(settings.LOGIN_REDIRECT_URL)
    context = {'form': form}
    return render(request, 'authentication/signup.html', context)


# def upload_profile_photo(request):
#     form = forms.UploadProfilePhotoForm()
#     if request.method == "POST":
#         form = forms.UploadProfilePhotoForm(request.POST, request.FILES)
#         if form.is_valid():
#             photo = form.save(commit=False)
#             photo.uploader = request.user
#             photo.save()
#             return redirect('home')
#     context = {"form": form}
#     return render(request, "blog/photo_upload.html", context)

@login_required
def upload_profile_photo(request):
    form = UploadProfilePhotoForm(instance=request.user)
    if request.method == 'POST':
        form = UploadProfilePhotoForm(
            request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('home')
    return render(request, 'authentication/upload_profile_photo.html', context={'form': form})

authentication/templates/authentication/login.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container-authentication">
        <section class="section-authentication">
            <h1>Login</h1>
            <p>{{ message }}</p>
            <form method='post' class="container">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_username">Username:</label>
                    <input type="text"
                           name="username"
                           class="form-control"
                           autofocus="true"
                           autocapitalize="none"
                           autocomplete="username"
                           required=""
                           id="id_username">
                </div>
                <div class="mb-3">
                    <label for="id_password">Password:</label>
                    <input type="password"
                           class="form-control"
                           name="password"
                           autocomplete="current-password"
                           required=""
                           id="id_password">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
                <p>
                    Not a member? <a href="{% url 'signup' %}">Sign up now!</a>
                </p>
            </form>
        </section>
    </div>
{% endblock content %}

authentication/templates/authentication/password_change_done.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <p>
        You have successfully changed you password! Click <a href={% url 'home' %}>here</a> to return to the homepage.
    </p>
{% endblock content %}

authentication/templates/authentication/password_change_form.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>Change your password</h2>
    <form class="form-upload" method="post">
        {% csrf_token %}
        <label for="id_old_password">Old password:</label>
        <input type="password"
               class="form-control"
               name="old_password"
               autocomplete="current-password"
               autofocus=""
               required=""
               id="id_old_password">
        <label for="id_new_password1">New password:</label>
        <input type="password"
               class="form-control"
               name="new_password1"
               autocomplete="new-password"
               required=""
               id="id_new_password1">
        <span class="helptext"></span>
        <ul>
            <li>Your password must contain at least one upper or lower case letter.</li>
            <li>Your password must contain at least one number.</li>
        </ul>
        <label for="id_new_password2">New password confirmation:</label>
        <input type="password"
               class="form-control"
               name="new_password2"
               autocomplete="new-password"
               required=""
               id="id_new_password2">
        <br>
        <button type="submit" class="btn btn-primary upload-btn">Submit</button>
    </form>
{% endblock content %}

authentication/templates/authentication/signup.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <section class="section-authentication">
        <h1 class="title-main">Sign Up</h1>
        {% if form.error %}{{ form.error }}{% endif %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Sign Up</button>
        </form>
        <p>
            Are you a member already? <a href="{% url "login" %}">Sign in now!</a>
        </p>
    </section>
{% endblock content %}

authentication/templates/authentication/upload_profile_photo.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <h2>Upload a Photo</h2>
    <form method="post" enctype="multipart/form-data" class="form-upload">
        {% csrf_token %}
        <label for="id_profile_photo">Profile photo:</label>
        <input class="form-control"
               type="file"
               name="profile_photo"
               accept="image/*"
               required=""
               id="id_profile_photo">
        <br>
        <button type="submit" class="btn btn-primary upload-btn">Submit</button>
    </form>
{% endblock content %}